name: Webtheme Default Content Recipe
description: A recipe to manage default webtheme content.
type: install
install:
  - node
  - block
  - ckeditor5
  - config
  - menu_link_content
  - block_content
  - editor
  - menu_link_content
  - token_filter
  - link_attributes
config:
  import:
    node: '*'
    block: '*'
    ckeditor5: '*'
    config: '*'
    menu_link_content: '*'
    block_content: '*'
    editor: '*'
    menu_link_content: '*'
    token_filter: '*'
    link_attributes: '*'
